@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "gabriel5@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "gabriel@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta 4 12",
  "content": "Contéudo da pergunta"
}

###

# @name fetch_recent_questions
Get {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_answer
Post {{baseUrl}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "authorId": "0375f155-cd8a-4cef-9b93-620c05d1bddf",
  "questionId":"f2447e91-eca2-4111-af33-b23ff4c3693d",
  "content": "Answer"
}

